name: Build and Publish Docker Images

on:
  push:
    branches: 
      - master
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [debian-xfce, debian-kde]

    env:
      APP_VERSION: "4.11.9"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=lscr.io/linuxserver/webtop:${{ matrix.variant }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/pandacoin-webtop:${{ matrix.variant }}-v${{ env.APP_VERSION }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/pandacoin-webtop:${{ matrix.variant }}-v${{ env.APP_VERSION }}
          push: true
